name: Self-Hosted Runner Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello from the self-hosted runner!"

      - name: List files
        run: ls -l
